version: "3"

tasks:
  init:
    cmds:
      - go install github.com/sqldef/sqldef/cmd/mysqldef@latest
  build:
    cmds:
      - docker compose -f compose-rust.yml build
    dir: ./development
  up:
    cmds:
      - docker compose -f compose-rust.yml up
    dir: ./development
    desc: "Start the application"
  down:
    cmds:
      - docker compose -f compose-rust.yml down -v --remove-orphans
    dir: ./development
  run:
    cmds:
      - task pre-bench
      - task bench
      - task post-bench
  pre-bench:
    cmds:
      - :>./webapp/logs/mysql/mysql-slow.log
      - :>./webapp/logs/nginx/access.log
      - :>./webapp/logs/nginx/error.log
  bench:
    cmds:
      - task run-local
    dir: ./bench
    desc: "Run benchmark"
  post-bench:
    cmds:
      - make post-bench-mysql
  migrate:
    deps:
      - up
    cmds:
      - sed /^USE\ isuride\;/d < webapp/sql/1-schema.sql | mysqldef -p isucon isuride
    sources:
      - webapp/sql/1-schema.sql
  go:build:
    cmd: go build -o isuride{{exeExt}} .
    dir: webapp/go
    sources:
      - ./*.go
      - go.mod
      - go.sum
  go:run:
    deps:
      - go:build
    cmd: ./isuride{{exeExt}}
    dir: webapp/go
  perl:run:
    cmd: carton exec plackup -s Starlet -p 8080 -Ilib -r app.psgi
    dir: webapp/perl
  build-image:
    cmd: docker build -f ./development/Dockerfile .
